import requests 

TOKEN = "eyJhbGciOiJFUzI1NiIsImtpZCI6ImExYTBjY2E2LWVlOTMtNDAwMS04YmMyLTE2MzcxYjQ3ZThiZSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3d3ZmZwYW5rYXZxcWlia29yb2J2LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI2MzY4MjhkYy0yM2E0LTRjYWEtOWQxZS0xMzliYzM5MmQ1ZmMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgwNjMxMzMwLCJpYXQiOjE3ODA2Mjc3MzAsImVtYWlsIjoic2NyZWVuemx4QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzgwNjI3NzMwfV0sInNlc3Npb25faWQiOiJlZGQyZGMyMC0yNTQ3LTRlMjEtODRhMS04ZGVkYmFkMDllMzIiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.k-CUUQB_vknA6wxSsx8wPuDqs_je_8CkvngZmP3J4WY2ZmbmjX2q7lRy_yTjJz8-cM_2sPANRqsA4GyoVVFKRA"

SUPABASE_URL = "https://wwffpankavqqibkorobv.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3ZmZwYW5rYXZxcWlia29yb2J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2MTE2ODAsImV4cCI6MjA5NjE4NzY4MH0.2STZI3ZSFyCW92ra1tMCuRuaTwoGlpPvoQUQvtHSMe0"

response = requests.get(
    f"{SUPABASE_URL}/auth/v1/user",
    headers={
        "Authorization": f"Bearer {TOKEN}",
        "apikey": SUPABASE_ANON_KEY,
    },
)

print(response.status_code)
print(response.json())