# Generated by Django 6.0.5 on 2026-05-22 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campeonatos', '0001_initial'),
        ('times', '0002_time_data_fundacao_time_estadio_time_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('AG', 'Aguardando'), ('AO', 'Ao Vivo'), ('EN', 'Encerrada')], default='AG', max_length=2)),
                ('gols_casa', models.IntegerField(default=0)),
                ('gols_visitante', models.IntegerField(default=0)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='campeonatos.campeonato')),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_casa', to='times.time')),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='times.time')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GOL', '⚽ Gol'), ('CAR', '🟨 Cartão Amarelo'), ('VER', '🟥 Cartão Vermelho'), ('SUB', '🔄 Substituição')], max_length=3)),
                ('minuto', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='partidas.partida')),
            ],
            options={
                'ordering': ['minuto'],
            },
        ),
    ]
