# Generated by Django 6.0.5 on 2026-05-22 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0001_initial'),
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='jogadores.jogador'),
        ),
    ]
