# Generated by Django 6.0.5 on 2026-05-22 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('times', '0002_time_data_fundacao_time_estadio_time_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('numero', models.IntegerField()),
                ('posicao', models.CharField(choices=[('GOL', 'Goleiro'), ('ZAG', 'Zagueiro'), ('LAT', 'Lateral'), ('VOL', 'Volante'), ('MEI', 'Meia'), ('ATA', 'Atacante')], max_length=3)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='times.time')),
            ],
        ),
    ]
