# Generated by Django 6.0.5 on 2026-05-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='data_fundacao',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='estadio',
            field=models.CharField(default='Estádio Não Informado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time',
            name='tecnico',
            field=models.CharField(default='Técnico Não Informado', max_length=100),
            preserve_default=False,
        ),
    ]
