# Generated by Django 6.0.5 on 2026-05-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_time_data_fundacao_time_estadio_time_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='escudos/'),
        ),
    ]
