# Generated by Django 6.0.5 on 2026-05-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('times', '0002_time_data_fundacao_time_estadio_time_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('times', models.ManyToManyField(blank=True, related_name='campeonatos', to='times.time')),
            ],
        ),
    ]
